### ISSUE TITLE
register component templates automatically (as partials)

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/amphora#362]
Once we deprecate `multiplex-templates`, we should register all components' handlebars templates as partials _automatically_

**Comment by jonwinton** [comment]
This will need to be re-examined based on the [Amphora Next](https://github.com/nymag/amphora/projects) project because this will be the concern of the [render package](https://github.com/nymag/amphora-html) that Amphora uses.

That being said, this will be a great optimization and will be much easier to implement with the new destructured render process.

**Comment by jonwinton** [comment]
Transferred issue to the new HTML render repo and will follow-up when that is implemented.
