### ISSUE TITLE
Amphora Bootstrapping

### ISSUE THREAD

**Issue by vicfriedman** [nymag/amphora#383]
Seems like all sites are referencing components on `bestofny`:

http://nymag.com/thecut/components/layout
http://nymag.com/daily/intelligencer/components/layout
http://nymag.com/selectall/components/layout
http://nymag.com/scienceofus/components/layout
http://grubstreet.com/components/layout
http://vulture.com/components/layout

The same thing happens with article.

I noticed this because of an issue with the `sponsored video lede` page type on the cut (http://nymag.com/thecut/pages/civo81rv7000bgsycbgta5ro4), which was created through the UI:

http://nymag.com/thecut/components/sponsored-video-lede - referencing `bestofny`

and the instance that page types is referencing betamale? http://nymag.com/thecut/components/sponsored-video-lede/instances/civo820bt0027c3yd4wacemun

**Comment by nelsonpecora** [comment]
I _think_ `files.getYaml` might be returning the same object when called from different sites, which would mean the prefixes would be mutating that object rather than setting them on new objects each time. That might be a thing to look into

**Comment by byronhulcher** [comment]
I've noticed that cloned components don't seem to be doing this, for instance http://nymag.com/selectall/components/article/instances/cj0o6skzz00fhfky6z8teybgy@published was published today at 3PM and all references to /selectall/ are intact

**Comment by jonwinton** [comment]
The issue was mutability (of course). The components were getting a their reference values mutated by the first site that Amphora found (determined by alphabetical order). The reason cloned components weren't having this issue is because we were cloning from a specific instance of a component (i.e. new page creation) and those component references are assigned in a different manner.
